### ISSUE TITLE
any news ?

### ISSUE THREAD

**Issue by niccolox** [ser/debops-lxd#1]
am just about to try  the same thing? 

any news on this?

**Comment by ser** [comment]
Hi, plans were ambitious, until I realised I need to create two containers a week in average.

My current steps are:

1. lxc launch ubuntu test1
2. adding static ip to its network/interfaces
3. adding a ssh key to root 
4. launching 'debops bootstrap' via ssh and automation works.

But if you have fresh scenarios how we can make it easier, let's discuss them and I will join our efforts.

**Comment by niccolox** [comment]
no worries, kind of in the same boat
